##########REGISTER
POST https://jobbyapp-backend.onrender.com/api/auth/register
Content-Type: application/json

{
  "name":"Akella Ravi Kiran",
  "email":"ravi@yopmail.com",
  "password":"Srinivas@8",
  "isEmployer":false,
  "profilePicture":"https://res-console.cloudinary.com/dakda5ni3/thumbnails/v1/image/upload/v1717485958/anlxZ2VpZndxa3RseXprZ3ZyN24=/as_is",
  "countryCode":"+91",
  "phone":"80767433212",
  "address":"11-220, venkat nagar, Indrapalem, Kakinada, Andhra Pradesh, - 533006"
}

######### LOGIN
POST https://jobbyappbackend-production.up.railway.app/api/auth/login
Content-Type: application/json

{
  "emailOrPhone":"srini@yopmail.com",
  "password":"Srinivas@8"
}

########### CREATE JOB
POST https://jobbyappbackend-production.up.railway.app/api/jobs/createJob
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzgyYTJjMjk4MzUzNjRmMWYxZWQyMzUiLCJpc0VtcGxveWVyIjp0cnVlLCJpYXQiOjE3MzgzNDI3OTh9.Fq2RVbMxuLvEaZ5ZR2YZ4XqIeShk9A8dW_jl-wsvb-c

{
  "role":"React Developer",
  "location":"Banglore, 66af212d2bbb209f920fea66Karnataka, India.",
  "skills":[1, 2, 3, 4, 5],
  "experience":[1, 2],
  "companyName":"Infosys Private Limited",
  "basicQualifications":[1, 2],
  "aboutTheCompany":"Infosys is a web and mobile app development company, dedicated to delivering software solutions that meet business needs. We offer complete end-to-end product development or can integrate with your existing product team.",
  "aboutTheJob":"We are looking for React and Node developers who are interested in experimentation and challenging the convention for our projects.",
  "userId":"6782a2c29835364f1f1ed235",
  "salary":"45,000/-",
  "companyLogo":""
}

######## GET JOBS
GET https://jobbyapp-backend.onrender.com/api/jobs/getJobs/66adf005dae0ac2bdd914701
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmFkZjAwNWRhZTBhYzJiZGQ5MTQ3MDEiLCJpc0VtcGxveWVyIjpmYWxzZSwiaWF0IjoxNzIyNjgxNDYyfQ.Fz32mk0mP_2iFRaJgFrQDeX1iIIN8aGfhospiM4rMsc


######### UPDATE JOB BY EMPLOYER
PATCH http://localhost:5000/api/jobs/update/6798fc18ecc9f0fa67b15ea1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzgyYTJjMjk4MzUzNjRmMWYxZWQyMzUiLCJpc0VtcGxveWVyIjp0cnVlLCJpYXQiOjE3MzgzNDE2MTF9.ESzYMaQnPqQdN6gMtpQImRkYCQjnTn1XYcEo9PWnnUA

{
  "role":"Backend Developer 2",
  "location":"Banglore, Karnataka, India.",
  "skills":[1, 2, 3],
  "experience":[1, 2],
  "companyName":"Appening Infotech",
  "basicQualifications":[1, 2, 5],
  "aboutTheCompany":"Appening is a web and mobile app development company, dedicated to delivering software solutions that meet business needs. We offer complete end-to-end product development or can integrate with your existing product team.",
  "aboutTheJob":"We are looking for NodeJs developers who are interested in experimentation and challenging the convention for our projects.",
  "userId":"66a65cd5aba9bf72a063c893",
  "salary":"45,000/-",
  "companyLogo":"https://media.licdn.com/dms/image/v2/D4D0BAQEL49-NBSRzaA/company-logo_200_200/company-logo_200_200/0/1705465857027/appeningxyz_logo?e=2147483647&v=beta&t=r1A9aPm2botlhp86PHcL6G-UItAAj2KerttqGG_hMEY"
}

###### APPLYING FOR A JOB
PATCH https://jobbyapp-backend.onrender.com/api/auth/apply/66af4c1bfe80406877bc70b1/66a66b044cfcb2ca8735ba7d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmE2NmIwNDRjZmNiMmNhODczNWJhN2QiLCJpc0VtcGxveWVyIjpmYWxzZSwiaWF0IjoxNzIyNjgyNjIwfQ.43aEq7vZRe1jpZpMQAjuDx7AzvEwY_VmfLg6n5mRyGM

########## DELETE THE JOB
DELETE https://jobbyapp-backend.onrender.com/api/jobs/delete/66ade253b140068217faa27b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmE2NWNkNWFiYTliZjcyYTA2M2M4OTMiLCJpc0VtcGxveWVyIjp0cnVlLCJpYXQiOjE3MjI2NzU2ODR9.FJv6R2BvZop4PEvzw69mjR_uiaSdiuIEDAcQs3W63rE

######## GET EMPLOYER JOBS
GET https://jobbyapp-backend.onrender.com/api/jobs/getJobs/66a65cd5aba9bf72a063c893?employerId=66a65cd5aba9bf72a063c893
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmE2NWNkNWFiYTliZjcyYTA2M2M4OTMiLCJpc0VtcGxveWVyIjp0cnVlLCJpYXQiOjE3MjIxODI5NDJ9.wY67GUbdi6h90aKw1Ksh6pI6uR1rZPWiscoAATitj4k

######## generate job description
POST https://jobbyapp-backend.onrender.com/api/jobs/generate-job-description
Content-Type: application/json

{
  "jobTitle":"MERN stack Developer with 2 years experience"
}

#######
PATCH http://localhost:5000/api/feed/update/6783f6508cc9c316c57edaa5/6782a2c29835364f1f1ed235
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzgyYTJjMjk4MzUzNjRmMWYxZWQyMzUiLCJpc0VtcGxveWVyIjp0cnVlLCJpYXQiOjE3MzcwNDIyNjd9.SPfSLMAXtwuaOQJKYGfzVZv-d6WReygzA4Bsm_GHWyo

{
  "title":"Updated Title"
}